version: 2

registries:
  python-codeartifact:
    type: python-index
    url: https://oaknorthbank-505282763753.d.codeartifact.eu-west-1.amazonaws.com/pypi/python-libraries/simple/
    username: aws
    password: ${{secrets.CODEARTIFACT_TOKEN}}

updates:
  - package-ecosystem: pip
    directory: "/"
    labels:
      - "dependencies"
      - "standard_change"
    registries:
      - python-codeartifact
    insecure-external-code-execution: allow
    schedule:
      interval: daily
      time: "09:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
